version: 2
jobs:
  build:
    working_directory: ~/circletest
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: postgres:9.6.1
        environmet:
        - POSTGRES_PASSWORD=pgpass
        - POSTGRES_DB=contract-test
        - LANG=ja_JP.UTF-8
    steps:
      - checkout
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential postgresql libpq-dev
  test:
    machine: True
    steps:
      - run: mvn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test