version: 2
jobs:
  build:
    working_directory: ~/circletest
    machine: true
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: |
            docker-compose -f env/local/docker/docker-compose.yml up -d
      - run:
          name: Run tests
          command: mvn test
      - run:
          name: Run tests2
          command: echo $SPRING_DATASOURCE_PASSWORD