version: 2
jobs:
  build:
    working_directory: ~/circletest
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: postgres:9.6.1
        environmet:
        - POSTGRES_PASSWORD=${PG_PASS}
        - POSTGRES_DB=contract-test
        - LANG=ja_JP.UTF-8
    steps:
      - checkout
      - run:
          name: Run tests
          command: mvn test
      - run:
          name: Run tests2
          command: echo ${PG_PASS}